import * as XLSX from 'xlsx';
import { EagleEyeDataset } from '../types';

export function exportAnalysisExcel(data: EagleEyeDataset) {
  const { metadata, evaluatedChecks, parameterStats, failures, totalEvaluated, passedCount, failedCount, passRate, categoryCounts } = data;
  const serial = metadata.serialNumber || 'CD04XB';
  const wo = metadata.workOrderNumber || 'WO2601284';

  const wb = XLSX.utils.book_new();

  // 1. Executive Summary Sheet
  const summaryAoa = [
    ['CDU FACTORY TEST REPORT — EAGLE EYE DIAGNOSTICS ANALYSIS'],
    ['Generated by:', 'Eagle Eye™ Diagnostics & Tolerance Margin Analyzer (Windows Application)'],
    ['Date Generated:', new Date().toLocaleString()],
    [],
    ['=== UNIT INFORMATION ==='],
    ['Unit Serial Number', metadata.serialNumber],
    ['Work Order Number', metadata.workOrderNumber],
    ['Customer', metadata.customer || 'GOOGLE'],
    ['Sequence Number', metadata.seqNumber || 'G592'],
    ['Software Version', metadata.softwareVersion],
    ['Framework / Build Version', metadata.frameworkBuildVersion],
    ['Tested By', metadata.testedBy],
    ['Date Tested', metadata.dateTested],
    [],
    ['=== TEST VERDICT & COMPLIANCE ==='],
    ['Final Test Result', metadata.finalResult.toUpperCase()],
    ['Total Diagnostic Checks', totalEvaluated],
    ['Passed Checks', passedCount],
    ['Failed Checks', failedCount],
    ['Compliance Pass Rate', `${passRate}%`],
    [],
    ['=== SUBSYSTEM FAILURE SUMMARY ==='],
    ['Hydraulic & Differential Pressure Failures', categoryCounts.hydraulic.fail],
    ['Pump & VFD Speed Violations', categoryCounts.pump.fail],
    ['Temperature Sensor Violations', categoryCounts.temperature.fail],
    ['Pressure Sensor Violations', categoryCounts.pressure.fail],
    ['Environmental Discrepancies (Air Humidity / Temp)', categoryCounts.environmental.fail],
    ['System & Configuration Discrepancies', categoryCounts.system.fail]
  ];
  const wsSummary = XLSX.utils.aoa_to_sheet(summaryAoa);
  XLSX.utils.book_append_sheet(wb, wsSummary, 'Executive Summary');

  // 2. Failure Diagnostics Punch-List (With Reason of Failure and What Range We Are Looking For)
  const failureHeaders = [
    'Time (sec)',
    'Target Flow (g/m)',
    'Target DP (PSI)',
    'Failed Parameter',
    'Category',
    'Unit',
    'Measured Value',
    'Value / Range We Are Looking For',
    'Lower 3σ Limit',
    'Upper 3σ Limit',
    'Deficit Amount',
    'Reason of Failure'
  ];

  const failureRows = failures.map(f => {
    const deficit = f.deltaLower !== null && f.deltaLower < 0 
      ? f.deltaLower 
      : (f.deltaUpper !== null && f.deltaUpper < 0 ? -f.deltaUpper : 0);

    return [
      f.timeSec,
      f.flowSp,
      f.dpSp,
      f.parameter,
      f.category,
      f.unit,
      f.measured,
      f.requiredRangeStr || 'N/A',
      f.lowLimit,
      f.highLimit,
      Number(deficit.toFixed(3)),
      f.failureReason || 'Failed specification check'
    ];
  });
  const wsFailures = XLSX.utils.aoa_to_sheet([failureHeaders, ...failureRows]);
  XLSX.utils.book_append_sheet(wb, wsFailures, 'Failure Diagnostics');

  // 3. Parameter Metrics Summary (Peak, Min, Settling, Range)
  const paramSummaryHeaders = [
    'Parameter / Sensor',
    'Category',
    'Unit',
    'Overall Test Peak (Max)',
    'Overall Test Minimum (Min)',
    'Final Settling Value (525s)',
    'Representative Required Range',
    'Worst-Case Margin Buffer',
    'Failed Checks Count',
    'Overall Sensor Verdict'
  ];

  const paramRows = Object.values(parameterStats).map(p => [
    p.name,
    p.category,
    p.unit,
    p.peak,
    p.min,
    p.settling,
    p.requiredRangeSample,
    p.worstMargin !== null ? Number(p.worstMargin.toFixed(3)) : '',
    p.failCount,
    p.status.toUpperCase()
  ]);
  const wsParamSummary = XLSX.utils.aoa_to_sheet([paramSummaryHeaders, ...paramRows]);
  XLSX.utils.book_append_sheet(wb, wsParamSummary, 'Parameter Metrics (Triad)');

  // 4. Detailed Step-by-Step Log
  const detailHeaders = [
    'Time (sec)',
    'Target Flow (g/m)',
    'Target DP (PSI)',
    'Target Temp (C)',
    'Parameter',
    'Category',
    'Unit',
    'Measured Value',
    'Lower 3σ Limit',
    'Upper 3σ Limit',
    'Delta Lower',
    'Delta Upper',
    'Margin Buffer',
    'Status'
  ];
  const detailRows = evaluatedChecks.map(c => [
    c.timeSec,
    c.flowSp,
    c.dpSp,
    c.tempSp,
    c.parameter,
    c.category,
    c.unit,
    c.measured,
    c.lowLimit,
    c.highLimit,
    c.deltaLower !== null ? Number(c.deltaLower.toFixed(3)) : '',
    c.deltaUpper !== null ? Number(c.deltaUpper.toFixed(3)) : '',
    c.marginBuffer !== null ? Number(c.marginBuffer.toFixed(3)) : '',
    c.status.toUpperCase()
  ]);
  const wsDetail = XLSX.utils.aoa_to_sheet([detailHeaders, ...detailRows]);
  XLSX.utils.book_append_sheet(wb, wsDetail, 'Full Step-by-Step Log');

  // Trigger download
  const outName = `EagleEye_Analysis_Report_${serial}_${wo}.xlsx`;
  XLSX.writeFile(wb, outName);
}
